In [ ]:
#Importing numpy
import numpy as np

#Numpy Arrays are faster than list

In [ ]:
from time import process_time
list_1=[i for i in range(10000)]
start=process_time()
list_2=[i+3 for i in list_1]
end=process_time()
print(end-start)

0.0006085540000011491


In [ ]:
np_array=np.array([i for i in range(10000)])
start=process_time()
np_array+=3 #another loop is not required
end=process_time()
print(end-start)

0.00016338400000037723


#Creation of Numpy Arrays

In [ ]:
np_array=np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)
#order of the array
np_array.shape

[1 2 3 4 5 6]


(6,)

In [ ]:
#Creating 2D Array
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.shape)
#Dimension of array
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [ ]:
#Creating a floating points array
b=np.array([(1,2,3),(4,5,8)],dtype=float)
print(b)

[[1. 2. 3.]
 [4. 5. 8.]]


#Initial Placeholders in Numpy Arrays

In [ ]:
#Numpy array of zeroes
a=np.zeros((3,2))
print(a) #datatype --> float
#Numpy array of 1
b=np.ones((3,2)) #datatype --> float
print(b)
#Numpy array of a particular value
c=np.full((3,2),8) #datatype --> int
print(c)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8]
 [8 8]
 [8 8]]


#Identity Matrix

In [ ]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#Numpy array with random values

In [ ]:
b=np.random.random((3,4)) #Values in the range 0-1 so floating numbers only
print(b)
c=np.random.randint(10,30,(3,4)) #matrix of 3*4 order with values between 10-30
print(c)

[[0.22654935 0.10916931 0.01174605 0.32506846]
 [0.33070362 0.38813076 0.42101758 0.79918969]
 [0.80607131 0.47172529 0.67092991 0.82552728]]
[[23 23 15 20]
 [18 21 12 21]
 [27 11 20 11]]


#Creating an evenly spaced  umpy array

In [ ]:
c=np.linspace(10,30,6) #no of elements specified
print(c)
d=np.arange(10,30,5) #step size specified
print(d)

[10. 14. 18. 22. 26. 30.]
[10 15 20 25]


#Converting a list to numpy array

In [ ]:
list_1=[10,20,30,40,50]
a=np.asarray(list_1)
print(a)

[10 20 30 40 50]


#Analysing a numpy array

In [ ]:
c=np.random.randint(10,30,(4,5))
#Dimension
print(c.ndim)
#No of elements
print(c.size)
#Datatype
print(c.dtype)

2
20
int64


#Mathematical Operation

In [ ]:
a=np.random.randint(10,30,(3,4))
b=np.random.randint(20,40,(3,4))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[30 59 68 64]
 [39 46 44 50]
 [60 38 48 55]]
[[-10 -13 -10  -8]
 [ -5 -16  -2  -2]
 [ -4 -14   2  -9]]
[[ 200  828 1131 1008]
 [ 374  465  483  624]
 [ 896  312  575  736]]
[[0.5        0.63888889 0.74358974 0.77777778]
 [0.77272727 0.48387097 0.91304348 0.92307692]
 [0.875      0.46153846 1.08695652 0.71875   ]]


#Array Manipulation


In [ ]:
c=a.T
print(c)
d=b.reshape(4,3)
print(d)

[[10 17 28]
 [23 15 12]
 [29 21 25]
 [28 24 23]]
[[20 36 39]
 [36 22 31]
 [23 26 32]
 [26 23 32]]
